name: Build APK with Docker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:v1.4.0

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build APK
        run: |
          yes | buildozer android debug
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: taskmanager-apk
          path: /home/user/hostcwd/bin/*.apk
